//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblModel()
        {
            this.TblUrun = new HashSet<TblUrun>();
        }
    
        public short ID { get; set; }
        public string ModelAdi { get; set; }
        public Nullable<short> MarkaID { get; set; }
        public string Ozellikleri { get; set; }
        public Nullable<decimal> AlisFiyati { get; set; }
        public Nullable<decimal> SatisFiyati { get; set; }
        public Nullable<int> Kategori { get; set; }
    
        public virtual TblKategori TblKategori { get; set; }
        public virtual TblMarka TblMarka { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblUrun> TblUrun { get; set; }
    }
}
