//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSatis
    {
        public int SatisID { get; set; }
        public Nullable<short> PersonelID { get; set; }
        public Nullable<int> MusteriID { get; set; }
        public Nullable<int> UrunID { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<short> Adet { get; set; }
    
        public virtual TblMusteri TblMusteri { get; set; }
        public virtual TblPersonel TblPersonel { get; set; }
        public virtual TblUrun TblUrun { get; set; }
    }
}
